# Generated by Django 6.0.6 on 2026-07-11 10:59

import hashlib

from django.db import migrations, models


def backfill_content_hashes(apps, schema_editor):
    DocumentChunk = apps.get_model("chats", "DocumentChunk")
    chunks = list(DocumentChunk.objects.filter(content_hash=""))
    for chunk in chunks:
        chunk.content_hash = hashlib.sha256(chunk.content.encode()).hexdigest()
    DocumentChunk.objects.bulk_update(chunks, ["content_hash"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_content_hashes, migrations.RunPython.noop),
    ]
